// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBempSmluNybqRULXi9hrRkRPRJGZI1XVY',
    appId: '1:560890166045:web:aea7915483afa98f6afff4',
    messagingSenderId: '560890166045',
    projectId: 'fir-flutter-udemy-4a5c2',
    authDomain: 'fir-flutter-udemy-4a5c2.firebaseapp.com',
    databaseURL: 'https://fir-flutter-udemy-4a5c2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-udemy-4a5c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATc5aotZ4Y5z0QWxOfbv7IX_QJjsqlG9Y',
    appId: '1:560890166045:android:798505349e7cab2a6afff4',
    messagingSenderId: '560890166045',
    projectId: 'fir-flutter-udemy-4a5c2',
    databaseURL: 'https://fir-flutter-udemy-4a5c2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-udemy-4a5c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaId4glF0deKkyC68qsqbwfwNSm6bw2M',
    appId: '1:560890166045:ios:4f2565042f172c756afff4',
    messagingSenderId: '560890166045',
    projectId: 'fir-flutter-udemy-4a5c2',
    databaseURL: 'https://fir-flutter-udemy-4a5c2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-udemy-4a5c2.appspot.com',
    androidClientId: '560890166045-pugbqppfbsan71rl05f39v89et1t0r00.apps.googleusercontent.com',
    iosClientId: '560890166045-bqqngq6sngte1poev9tjdvseihmov6f9.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielhrp31.firebase',
  );
}
